export const environment = {
  production: false,
  API_URL: 'https://app.tybo.co.za/',
  // BASE_URL: 'https://tybofashion.co.za',
  // API_URL: 'https://tybofashion.co.za/api',
  // BASE_URL: 'https://tybofashion.co.za',
  // API_URL: 'http://localhost:8200/api-tybo-accounting',
  BASE_URL: 'http://localhost:4200',
  BASE_URL_ADMIN: 'http://localhost:4200',
  ACCOUNT_TEST_EMAIL: 'ndumiso@tybo-accoutning.co.za',
  ACCOUNT_TEST_PASSWORD: 'ndumiso@tybo-accoutning.co.za',
  TEST_EMAIL_ACCOUNT: 'admin@tybo-services.co.za',
  DF_LOGO: `https://app.tybo.co.za//api/upload/uploads/1616127224newlogo.png`,
  DF_USER_LOGO: `https://app.tybo.co.za//api/upload/uploads/1616127548iio.jpg`,
};
